linters:
  enable:
    - gofmt
    - govet
    - gosimple

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused
        - staticcheck
    - linters:
        - errcheck
      text: "Error return value of"
    - linters:
        - unused
      text: "is unused"

run:
  timeout: 5m
