linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  max-issues-per-linter: 50
  max-same-issues: 10

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - node_modules
